name: custom_alert_snackbar
description: A package for developing a personalized snackbar
version: 1.0.3
autor: Hallan Abreu
homepage: https://github.com/hallanabreu2020/custom_alert_snackbar

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter_svg: '>=2.0.9 <3.0.0'
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/
